file:
  # размеры для файлов к посту
  # размеры файла
  max-size-image: 5832000
  max-size-video: 52428800
  max-size-audio: 10485760
  # максимальное кол-во файлов при добавлении к посту
  max-count-files: 10
  # соотношение сторон изображения
  max_vertical_width: 1080
  max_vertical_height: 1080
  max_horizontal_width: 1080
  max_horizontal_height: 566

auto-start-syntax:
  # проверка постов на ошибки
  # запускать каждый день в 00:00
  cron: 0 0 0 * * *

auto-checking-posts-by-verification:
  cron: 0 0 12 * * *

size:
  not-verified-posts-for-users:
    size: 5